spring.profiles.active=local
spring.security.user.name=user
spring.security.user.password={noop}1234
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.application.name=smartstudy
